"""add gimbal_pitch to waypoint

Revision ID: f341383d7ac2
Revises: a1b2c3d4e5f6
Create Date: 2026-03-15 15:36:10.707178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = 'f341383d7ac2'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waypoint', sa.Column('gimbal_pitch', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waypoint', 'gimbal_pitch')
    # ### end Alembic commands ###
