"""add tolerance to lha

Revision ID: f7c0935d47ec
Revises: eec7d1c63489
Create Date: 2026-04-12 14:12:33.915098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = 'f7c0935d47ec'
down_revision: Union[str, None] = 'eec7d1c63489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lha', sa.Column('tolerance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lha', 'tolerance')
    # ### end Alembic commands ###
